#!/usr/bin/env ruby
# automate the running & evaluating of an FoCW run
#
# Usage: ./run_focw <path/to/target/corpus>

input = ARGV.shift
threshold = ARGV.empty? ? "0.0" : ARGV.shift
`./focw #{input} #{threshold}> #{input}.focw`
threshold.gsub(".","_")
`ruby scripts/apply_wordmap.rb #{input} | ruby scripts/evaluate.rb > #{input}.#{threshold}.fscore`
`mv #{input}.focw #{input}.#{threshold}.focw`
puts `cat #{input}.#{threshold}.fscore`
`mv temp.yaml #{input}.#{threshold}.yaml`
